# Workflow for the api of colet.

name: API CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Nodejs
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14.x
          
      - name: Installing Dependencies
        working-directory: ./api
        run: |
          npm ci
      - name: Eslint
        working-directory: ./api
        run: |
          npm run lint
      - name: Set up local MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - name: Jest
        working-directory: ./api
        run: |
          npm run test
        env:
          DB_TEST_CONNECTION: mongodb://127.0.0.1:27017/%DB_NAME%